package com.raen.optidroid.data.repository


import com.raen.optidroid.BuildConfig
import com.raen.optidroid.domain.model.common.AppInfo
import com.raen.optidroid.domain.model.common.Resource
import com.raen.optidroid.domain.repository.AppInfoRepository
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Data layer implementation of [AppInfoRepository] that exposes build metadata
 * generated by Gradle through [BuildConfig].
 *
 * This repository isolates Android framework dependencies from the domain
 * while providing the current version name and code for display in Settings
 * or about screens.
 *
 */
@Singleton
class AppInfoRepositoryImpl @Inject constructor() : AppInfoRepository {

    /**
     * Loads the version name and version code embedded in the current build by
     * Gradle. They therefore always match the APK being executed.
     *
     * @return [Resource.Success] containing [AppInfo] when the package info is
     * resolved from the generated build configuration.
     */
    override suspend fun getAppInfo(): Resource<AppInfo> {
        return Resource.Success(
            AppInfo(
                versionName = BuildConfig.VERSION_NAME,
                versionCode = BuildConfig.VERSION_CODE.toString()
            )
        )
    }
}
