package com.raen.optidroid.domain.model.common

/**
 * Represents static application metadata used for displaying build information
 * to the user within the Settings or About screens.
 *
 * @property versionName Human-readable application version name (e.g. "1.0.0").
 * @property versionCode Internal version code generated by Gradle for this build.
 */
data class AppInfo(
    val versionName: String,
    val versionCode: String
)
